<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>Zeiss.PiWeb.Sdk.Import.Tests</AssemblyName>
    <RootNamespace>Zeiss.PiWeb.Sdk.Import.Tests</RootNamespace>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" Version="9.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NUnit" Version="4.4.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.1.0" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\PiWeb.Sdk.Import\PiWeb.Sdk.Import.csproj" />
  </ItemGroup>
  
</Project>
