<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  
  <PropertyGroup>
    <!-- Whether to create a .pip package file when building -->
    <GeneratePluginPackageOnBuild Condition=" '$(GeneratePluginPackageOnBuild)' == '' ">false</GeneratePluginPackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <UpToDateCheckInput Include="$(ProjectDir)\manifest.json" />
    <UpToDateCheckOutput Include="$(PackageOutputPath)\$(AssemblyName)@$(Version).pip" />
  </ItemGroup>
  
  <!-- Calls _GeneratePluginPackage after building when 'GeneratePluginPackageOnBuild' == true -->
  <Target Name="PackPluginAfterBuild"
          AfterTargets="Build"
          Condition=" '$(GeneratePluginPackageOnBuild)' == 'true' "
          DependsOnTargets="_GeneratePluginPackage">
  </Target>

  <!-- This target can be manually called to pack the project as .pip package file -->
  <Target Name="PackPlugin" 
          DependsOnTargets="Build;_GeneratePluginPackage">
  </Target>

  <!-- Creates a .pip package file for the project -->
  <Target Name="_GeneratePluginPackage" 
          DependsOnTargets="Build">

    <ItemGroup>
      <PipFiles Exclude="$(OutDir)\*.pip" Include="$(OutDir)\**\*" />
    </ItemGroup>

    <Message Text="Removing previously created staging directory."
             Importance="low" />
    <RemoveDir Directories="$(IntermediateOutputPath)\PipStaging" />

    <Message Text="Copying build output to '$(IntermediateOutputPath)\PipStaging'."
             Importance="low" />
    <Copy SourceFiles="@(PipFiles)" DestinationFolder="$(IntermediateOutputPath)\PipStaging" />
    
    <ZipDirectory SourceDirectory="$(IntermediateOutputPath)\PipStaging"
                  DestinationFile="$(PackageOutputPath)\$(AssemblyName)@$(Version).pip"
                  Overwrite="true" />
    
    <Message Text="Successfully created plugin package '$(PackageOutputPath)\$(AssemblyName)@$(Version).pip'."
             Importance="high" />
             
  </Target>
  
</Project>